### ISSUE TITLE
Run on sentence

### ISSUE THREAD

**Issue by jeankaplansky** [w3c/epubweb#13]
"EPUB can be considered to be at an inflection point. EPUB has been broadly adopted on a global basis for “trade” eBooks, and is beginning to be adopted for e-textbooks and other types of documents, but has been largely an “offline” format. "

How about:

"EPUB can be considered to be at a tipping point. EPUB has been broadly adopted globally for trade ebooks, and is starting to gain adoption among textbook publishers as well as corporate marketing departments. However, EPUB has largely been seen as an "offline" format up until now."

**Comment by iherman** [comment]
Related to issue #12

**Comment by iherman** [comment]
Changed. I have also changed the 'inflection' to 'tipping' in the paragraph after this one. This also closes issue #12
