### ISSUE TITLE
reword - again on the passive.

### ISSUE THREAD

**Issue by jeankaplansky** [w3c/epubweb#14]
"While various browser extensions supporting EPUB exist (Readium-Chrome, EPUB-Firefox, .etc.), as well as solutions for delivering EPUB files in browsers (Readium-Cloud, EPUB.js, Safari Books Online, etc.) these solutions require relatively complex server and/or client software and in some cases depend on non-standardized transformation of packged .epub files into more network-delivery-suitable forms."

How about "Various browser extensions supporting EPUB exist (Readium in Chrome, EPUB in Firefox, et al.). Other solutions exist for delivering EPUB files in browsers (Readium0Cloud, EPUB.js Safari Books Online, et al.). Browser- and cloud-based solutions require relatively complex server and/or client software. In many cases browser- and cloud-based solutions depend on a proprietary transformation of the packaged EPUB files into formats more suitable to network delivery."

**Comment by iherman** [comment]
Sounds much better. Changed.
