### ISSUE TITLE
More to re-word.

### ISSUE THREAD

**Issue by jeankaplansky** [w3c/epubweb#15]
"A focused effort to make EPUB a first-class citizen of the Open Web Platform and as a result significantly reduce the complexity of deploying EPUB content into browsers, for online as well as offline consumption, would increase momentum for EPUB and associated Web Standards adoption in the many communities who are are looking for an open, non-proprietary, next-generation portable document format."

"A focused effort to make EPUB a first-class Open web Platform citizen will result in significant reduction in the complexity of deploying EPUB content into browsers for both online and offline consumption. Further, this focused effort will increase the momentum of EPUB and associated web adoption across communities who are..." (do something about that "next-generation portable document format." Too many people will think PDF as a knee jerk reaction just to seeing the words.

**Comment by iherman** [comment]
Made the change. The terminology issue about "Portable Document Format" is left to issue #4 should be treated separately
