### ISSUE TITLE
More grammar/re-wording

### ISSUE THREAD

**Issue by jeankaplansky** [w3c/epubweb#18]
"However, the specific means of delivering such hybrid and Web-technology-based system applications is presently proprietary to particular application and/or browser platforms. Working on EPUB-WEB will increase momentum in solving problems in packaging, metadata, and offline support applicable to both portable documents and installed applications and help ensure the broadest possible adoption for the Open Web Platform in general."

to 

"The specific means of delivering hybrid and web-technology-based system applications is currently proprietary to specific applications frameworks and/or browser platforms. The point of EPUB-WEB is to increase problem solving momentum in package, metadata, and offline support applicable to both portable documents and install applications. Open and native solutions to replace proprietary packaging, metadata, and offline support are intended to ensure the broadest possible general adoption OF the Open Web Platform."

**Comment by iherman** [comment]
Changed (with a minor additional change: 'install application' -> 'installed application')
