### ISSUE TITLE
new use cases: stable references/citations

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epubweb#2]
An additional use case that would be extremely valuable to academic and scholarly publishing is stable references and citations. There are currently several methods for citing online works (disputed among style guides), but there is no standard method for citations in ebooks. Even if a reflowable ebook is by a scholar, she must refer to PDF, paper copy, or HTML version to cite it in her bibliography. EPUB-Web should enable stable citations.

**Comment by iherman** [comment]
I have added a reference to this in the new version (January '15)
