### ISSUE TITLE
EPUB3 for Integrated and Customizable Representation of a Scientific Publication and its Associated Resources

### ISSUE THREAD

**Issue by Bahar1978** [w3c/epubweb#23]
Scientific publications point to many associated resources,
including videos, prototypes, slides, and datasets. However, discovering
and accessing these resources is not always straightforward: links
could be broken, readers may be offline, or the number of associated
resources might make it difficult to keep track of the viewing order. In
this paper, we explore potential integration of such resources into the
digital version of a scientific publication. Specifically, we evaluate the
most common scientific publication formats in terms of their capability
to implement the desirable attributes of an enhanced publication and to
meet the functional goals of an enhanced publication information system:
PDF, HTML, EPUB2, and EPUB3. In addition, we present an
EPUB3 version of an exemplary publication in the field of computer
science, integrating and interlinking an explanatory video and an interactive
prototype. Finally, we introduce a demonstrator that is capable
of outputting customized scientific publications in EPUB3. By making
use of EPUB3 to create an integrated and customizable representation
of a scientific publication and its associated resources, we believe that
we are able to augment the reading experience of scholarly publications,
and thus the effectiveness of scientific communication.

http://linkedscience.org/wp-content/uploads/2014/10/lisc2014_submission_3.pdf

**Comment by iherman** [comment]
Added a reference to this paper; see pull request #39. Closing the issue.

/Cc @hajarghaem
