### ISSUE TITLE
Reference the Service Workers (draft) spec ?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubweb#29]
[Service Workers](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/) is one of the possible technical answers to improving offline use of web apps.

I'm not quite sure how it fits with the Packaging spec, and it's probably more geared towards enabling an _offline_ use of web content than enabling a _portable_ package, but I believe it is certainly a spec to watch and which may play a role in EPUB-WEB.

**Comment by iherman** [comment]
Sure, it is something to watch. But I am not sure how, I must admit. The way I understand the service worker stuff is that it would be a tool in _implementing_ offline use, but I am not sure it influences the specification level designs...

**Comment by rdeltour** [comment]
Yes, I do not have a clear idea either. One thing that will have to be thought about at spec design is whether EPUB-WEB authors are "allowed" to use Service Workers (if it's all OWP, why not?) or if such mechanisms are more targeted at RS developers, and what's the implications on online/offline/portable transition.

**Comment by iherman** [comment]
Having looked at the [Service Workers Specification](http://www.w3.org/TR/service-workers/) and trying to understand it (I do not think I have really got everything in it...) I would expect that the _packaging_ stuff will be implemented by Service Workers, at the minimum. But sounds, sort of, quite a logical approach to have a SW do the unpackaging, spreading the various files into, say, some client side storage and let the 'main' part of the browser take it from there. In this sense, an EPUB-WEB instance would indeed be, partially, done in an SW.

I think this is not something we should worry about for now; SW is still very much in a development phase. As you said, it SW may play a role in future.

**Comment by iherman** [comment]
I would propose to keep this on hold for now. Yes, SW is a technology that may influence the evolution of, eg, packaging, but it is too much of a technical detail for the White Paper in my view.

**Comment by iherman** [comment]
I have added my [notes on Web and Service Workers](https://github.com/w3c/epubweb/wiki/Notes-on-Web-and-Service-Workers) on the wiki.
