### ISSUE TITLE
Reference the Manifest for web application spec ?

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubweb#30]
[Manifest for web application](https://w3c.github.io/manifest/) "defines a JSON-based manifest that provides developers with a centralized place to put metadata associated with a web application".

I would very well see it as a potential spec to use in EPUB-WEB, e.g. to describe what's needed in [section 3.2 "Capturing overall publication structure"](https://w3c.github.io/epubweb/#capturing-overall-publication-structure).

**Comment by iherman** [comment]
Thanks for the pointer, this is indeed very useful, potentially. Would that replace the current `opf` files, potentially?

My very cursory reading of the spec reveals a difference in view, however. In some sense, an EPUB "begins" with the manifest files, that is the file that governs/gives information on what is in the EPUB file, what types they are, etc. Using the manifest as in this referred spec puts an HTML file into the center as the starting point, linking to additional metadata that gives all those information. I am not sure what the consequences are, though...

**Comment by rdeltour** [comment]
> Would that replace the current opf files, potentially?

yes, from what I understand the manifest for web apps is roughly the equivalent to the OPF for EPUBs.

> My very cursory reading of the spec reveals a difference in view, however.

Right. Note that there's an interesting recent [thread in the `www-tag` list about the Packaging spec](https://lists.w3.org/Archives/Public/www-tag/2015Jan/0121.html) which mentions a manifest-like approach and asks the question of intersection with the Manifest spec.
I've not read the whole thread, but it's definitely of interest for EPUB-WEB.

**Comment by mgylling** [comment]
Added in https://github.com/w3c/epubweb/commit/d79e1357595682316604884f5f189a5a5fc3f59c

LMKWYT.

**Comment by rdeltour** [comment]
LGTM (except perhaps the extra `<p>` starting tag)
