### ISSUE TITLE
user privacy and DRM intermingled

### ISSUE THREAD

**Issue by mgylling** [w3c/epubweb#31]
... these are different topics, but are intermingled in the text

http://w3c.github.io/epubweb/#security-and-privacy-models

**Comment by mgylling** [comment]
Addressed in https://github.com/w3c/epubweb/commit/8f801ec361e49fab5bc0fb55cbd7c81f4e41770f

There is no DRM talk whatsoever now, only security and privacy.  @iherman, ok with this?

**Comment by iherman** [comment]
It may come back to haunt us, but it is o.k. for now.
