### ISSUE TITLE
a couple of use cases.

### ISSUE THREAD

**Issue by tmichel07** [w3c/epubweb#32]
An interesting use case are documents including forms, that one may want to download from the web and fill in locally and off line, and resend the filled form as a package. This could probably be achived with EPUB-WEB, with the OWP technologies.

So maybe adding a few words about forms could be of interest.

Another use case are documents for which the editor wants to add protection (with a password or not allowing copy& paste, etc).
 These are available in PDF and would also be of great interest.

Last is downloading of a subset of pages of a book in an EPUB
package. But maybe this is part of section "3.3 Document and fragment
identification"

**Comment by iherman** [comment]
This is a duplication of issue #1; closing it
