### ISSUE TITLE
Do we want to use the Wiley Java book as an example?

### ISSUE THREAD

**Issue by iherman** [w3c/epubweb#34]
I am thinking of the video at http://www.wiley.com/college/sc/horstmann/. This is a perfect example where, apart from running on line, there is really nothing that differentiate this book from a well done interactive Web page... which is exactly the EPUB-WEB issue:-)

**Comment by TzviyaSiegman** [comment]
Good idea. I will look into it. I have other examples as well.

**Comment by uptownnickbrown** [comment]
Big Java is a great example of book content that works equally well in a web context.

It's interesting to look at the opposite perspective as well - there are lots of interactive Web pages that would make great books for offline use. For example, just looking at educational interactive content:
- http://bost.ocks.org/mike/algorithms/
- https://jackschaedler.github.io/circles-sines-signals/index.html
- http://worrydream.com/LadderOfAbstraction/
- http://setosa.io/ev/markov-chains/

I mention it because moving from a website to a packaged document seems much more complex than vice versa. You have to handle links, 3rd-party dependencies (eg. js libraries), etc. It could be interesting to consider examples of moving in both directions across the EPUB-WEB boundary.

**Comment by iherman** [comment]
> On 10 Mar 2015, at 19:28 , Nick Brown notifications@github.com wrote:
> 
> Big Java is a great example of book content that works equally well in a web context.
> 
> It's interesting to look at the opposite perspective as well - there are lots of interactive Web pages that would make great books for offline use. For example, just looking at educational interactive content:
> 
>   • http://bost.ocks.org/mike/algorithms/
>   • https://jackschaedler.github.io/circles-sines-signals/index.html
>   • http://worrydream.com/LadderOfAbstraction/
>   • http://setosa.io/ev/markov-chains/

I knew the first one (which is actually referred to from the document) but not the other three. And yes, these are great examples for articles that could make it to an offline document.

> I mention it because moving from a website to a packaged document seems much more complex than vice versa. You have to handle links, 3rd-party dependencies (eg. js libraries), etc. It could be interesting to consider examples of moving in both directions across the EPUB-WEB boundary.

Indeed. But note that many of the browsers have actually solved the problem already, insofar as they offer the possibility to store some sort of an offline version of a page ("Web Page, Complete", as it is referred to in the menu by Firefox). It is just that all of them use a different way of storing the result. It would be a, comparatively, tiny step to store this in a standard and interoperable way...

Thanks!

ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
@TzviyaSiegman : what is the official reference to be used for the Java book? Ie, a URI... (I hope there is one for it, otherwise a page on Wiley's site?)

**Comment by TzviyaSiegman** [comment]
See http://bcs.wiley.com/he-bcs/Books?action=index&bcsId=7005&itemId=1118087887. Some of materials are PDFs, but many link to video, etc (see "more information")

**Comment by iherman** [comment]
Closed by virtue of the merged pull request #36. Thanks to @TzviyaSiegman for the link; I have also incorporated some links provided by  @uptownnickbrown

**Comment by uptownnickbrown** [comment]
👍 - nice addition.

To your earlier point, yes, browsers attempt to do this today. In addition to the lack of interoperability, the process often breaks the functionality of complex pages. Of course a standard way to do it could help on the quality side of things as well as being interoperable.
