### ISSUE TITLE
more wordsmithing

### ISSUE THREAD

**Issue by jeankaplansky** [w3c/epubweb#6]
"EPUB is built on Web Standards, and the individual items that make up an EPUB publication are exactly the same types of content that make up a Web site: [HTML5], [SVG], [CSS21], [ECMAScript], [JPEG] and [PNG] images, etc."

Why not just say "EPUB is built on Web Standards, and the individual items that make up an EPUB publication are identical to types of content on a Web site:...."

**Comment by iherman** [comment]
Done.
