### ISSUE TITLE
Wordsmithing 4

### ISSUE THREAD

**Issue by jeankaplansky** [w3c/epubweb#8]
"While Web documents and portable documents have distinguishing characteristics, the differences can also be viewed as situational and gradual rather than representing bright-line distinctions."

How about "The differences between the distinguishing characteristics of web documents and portable document can be viewed as situational and gradual rather than as representative of bright-line distinctions."

(Someone beat me over the head with a red marker about passive voice one. Not really. But they did instill the point about avoid the passive...)

**Comment by iherman** [comment]
No doubt this sounds better! Done.
